// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AdminOrderInfoReq struct {
	UserId string `form:"userId"`
	Page   int    `form:"page"`
	Size   int    `form:"size"`
}

type AdminOrderInfoResp struct {
	TotalNo int         `json:"totalno"`
	Orders  []OrderInfo `json:"orders"`
}

type DishInfo struct {
	Id          int     `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Category    string  `json:"category"`
	Ingredients string  `json:"ingredients"`
	ImageUrl    string  `json:"imageurl"`
}

type DishInfoResp struct {
	Categories []string   `json:"categories"`
	DishList   []DishInfo `json:"dishlist"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId   string  `json:"userId"`
	Username string  `json:"username"`
	Usertype string  `json:"usertype"`
	Balance  float64 `json:"balance"`
	Token    string  `json:"token"`
}

type ModifyBalanceReq struct {
	AdminId  string  `json:"adminId"`
	Username string  `json:"username"`
	Balance  float64 `json:"balance"`
}

type ModifyBalanceResp struct {
	UserId  string  `json:"userId"`
	Balance float64 `json:"balance"`
}

type OrderCompleteReq struct {
	UserId      string `json:"userId"`
	OrderUserId string `json:"orderUserId"`
	OrderId     int64  `json:"orderId"`
}

type OrderCompleteResp struct {
	TotalNo int `json:"totalno"`
}

type OrderInfo struct {
	OrderId    int64           `json:"orderid"`
	Status     string          `json:"status"`
	UserId     string          `json:"userId"`
	Username   string          `json:"username"`
	Items      []OrderInfoItem `json:"items"`
	TotalPrice float64         `json:"totalprice"`
	CreateTime string          `json:"createtime"`
	PickupTime string          `json:"pickupTime"`
}

type OrderInfoItem struct {
	Id    int    `json:"id"`
	Name  string `json:"name"`
	Count int    `json:"count"`
}

type OrderInfoReq struct {
	UserId string `form:"userId"`
	Page   int    `form:"page"`
	Size   int    `form:"size"`
}

type OrderInfoResp struct {
	Orders []OrderInfo `json:"orders"`
}

type OrderItem struct {
	Id    int     `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
	Count int     `json:"count"`
}

type PayOrderReq struct {
	UserId     string      `json:"userId"`
	Items      []OrderItem `json:"items"`
	TotalPrice float64     `json:"totalprice"`
	PickupTime string      `json:"pickupTime"`
}

type PayOrderResp struct {
	Balance float64 `json:"balance"`
}

type RegisterReq struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	Invitecode string `json:"invitecode"`
}

type RegisterResp struct {
}

type UploadDishResp struct {
	OK int `json:"ok"`
}
