// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	account "canteen-api/internal/handler/account"
	admin "canteen-api/internal/handler/admin"
	dish "canteen-api/internal/handler/dish"
	order "canteen-api/internal/handler/order"
	"canteen-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: account.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: account.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/menu/dish",
				Handler: admin.AddDishesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/order/complete",
				Handler: admin.OrderCompleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/order/info",
				Handler: admin.GetOrderInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/user/balance",
				Handler: admin.ModifyBalanceHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/dish/info",
				Handler: dish.GetDishInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/order/info",
				Handler: order.GetOrderInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/pay",
				Handler: order.PayOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
